<?php

/**
 * @file
 * This file helps getting familiar with hooks.
 */

/**
 * Implements hook_cron().
 */
function dummy_module_cron() {
  \Drupal::messenger()->addMessage(t('Hello there! This is the dummy_module adding a message after ever cron run.'));
}

/**
 * Implements hook_form_alter().
 */
function dummy_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // \Drupal::messenger()->addMessage(t("form_id is: @id", ['@id' => $form_id]));
  if ($form_id === 'node_article_edit_form') {
     $form['actions']['submit']['#value'] = t('THIS IS TOTALLY NOT THE SAVE BUTTON !!');
  }
}
